/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AvatarButton: typeof import('./src/pages/Home/components/AvatarButton.vue')['default']
    BaseInput: typeof import('./src/components/Input/BaseInput.vue')['default']
    CarImage: typeof import('./src/pages/Home/components/CarImage.vue')['default']
    Clients: typeof import('./src/pages/Home/views/Clients.vue')['default']
    ClientsTable: typeof import('./src/pages/Home/components/ClientsTable.vue')['default']
    Components: typeof import('./src/pages/UILibrary/Components.vue')['default']
    DatePickerInput: typeof import('./src/components/Input/DatePickerInput.vue')['default']
    ExtraSmallButton: typeof import('./src/components/Button/ExtraSmallButton.vue')['default']
    FilterStatusInfo: typeof import('./src/pages/Home/components/FilterStatusInfo.vue')['default']
    Home: typeof import('./src/pages/Home/Home.vue')['default']
    HomeHeader: typeof import('./src/pages/Home/components/HomeHeader.vue')['default']
    HomeLayout: typeof import('./src/layouts/HomeLayout.vue')['default']
    HomeView: typeof import('./src/pages/Home/views/HomeView.vue')['default']
    Login: typeof import('./src/pages/Login/Login.vue')['default']
    MainLayout: typeof import('./src/layouts/MainLayout.vue')['default']
    NavBarButton: typeof import('./src/pages/Home/components/NavBarButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollableContainer: typeof import('./src/components/ScrollableContainer.vue')['default']
    SearchInput: typeof import('./src/components/Input/SearchInput.vue')['default']
    SpecialButton: typeof import('./src/components/Button/SpecialButton.vue')['default']
    StationDetailsDrawer: typeof import('./src/pages/Home/components/Stations/StationDetailsDrawer.vue')['default']
    Stations: typeof import('./src/pages/Home/views/Stations.vue')['default']
    StationsSidebar: typeof import('./src/pages/Home/components/StationsSidebar.vue')['default']
    StationTable: typeof import('./src/pages/Home/components/StationTable.vue')['default']
    TableLoadingSkeleton: typeof import('./src/pages/Home/components/TableLoadingSkeleton.vue')['default']
  }
}
